services:
  bus-speed-processor:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    env_file:
      - .env
    restart: "no"

